// Auto-generated by supabase gen types. Hand-written mirror — will be overwritten by npm run gen:types.

export interface ApplicationStep {
  step: number;
  title: string;
  description: string;
}

export interface CountriesRow {
  id: string;
  slug: string;
  flag_emoji: string | null;
  hero_image_url: string | null;
  sort_order: number | null;
  is_active: boolean | null;
  is_featured: boolean | null;
  name_az: string;
  name_ru: string | null;
  name_en: string | null;
  description_az: string | null;
  description_ru: string | null;
  description_en: string | null;
  warning_banner_az: string | null;
  warning_banner_ru: string | null;
  warning_banner_en: string | null;
  advantages_az: string[] | null;
  advantages_ru: string[] | null;
  advantages_en: string[] | null;
  documents_az: string[] | null;
  documents_ru: string[] | null;
  documents_en: string[] | null;
  steps_az: ApplicationStep[] | null;
  steps_ru: ApplicationStep[] | null;
  steps_en: ApplicationStep[] | null;
  qs_universities: number | null;
  qs_avg_tuition_usd: number | null;
  qs_language: string | null;
  qs_visa_difficulty: "easy" | "medium" | "hard" | null;
  created_at: string | null;
  updated_at: string | null;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface UniversitiesRow {
  id: string;
  slug: string;
  country_slug: string;
  website_url: string | null;
  logo_url: string | null;
  hero_image_url: string | null;
  is_active: boolean | null;
  is_featured: boolean | null;
  name_az: string;
  name_ru: string | null;
  name_en: string | null;
  city_az: string;
  city_ru: string | null;
  city_en: string | null;
  highlights_az: string[] | null;
  highlights_ru: string[] | null;
  highlights_en: string[] | null;
  notes_az: string;
  notes_ru: string;
  notes_en: string;
  campus_info_az: string;
  campus_info_ru: string;
  campus_info_en: string;
  created_at: string | null;
  updated_at: string | null;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface FacultiesRow {
  id: string;
  university_slug: string;
  name_az: string;
  name_ru: string | null;
  name_en: string | null;
  is_competitive: boolean | null;
  duration_years: number | null;
  language: string | null;
  sort_order: number | null;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface UniversityFeesRow {
  university_slug: string;
  tuition_min_usd: number;
  tuition_max_usd: number;
  dorm_min_usd: number;
  dorm_max_usd: number;
  food_min_usd: number;
  food_max_usd: number;
  transport_min_usd: number;
  transport_max_usd: number;
  personal_min_usd: number;
  personal_max_usd: number;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface FaqsRow {
  id: string;
  country_slug: string | null;
  university_slug: string | null;
  question_az: string;
  question_ru: string | null;
  question_en: string | null;
  answer_az: string;
  answer_ru: string | null;
  answer_en: string | null;
  sort_order: number | null;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface TestimonialsRow {
  id: string;
  student_name: string;
  university_slug: string | null;
  country_slug: string | null;
  photo_url: string | null;
  quote_az: string;
  quote_ru: string | null;
  quote_en: string | null;
  year: number | null;
  is_active: boolean | null;
  sort_order: number | null;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface SiteContentRow {
  key: string;
  value_az: string;
  value_ru: string | null;
  value_en: string | null;
  updated_at: string | null;
  is_deleted: boolean;
  deleted_at: string | null;
}

export interface ApplicationsRow {
  id: string;
  full_name: string;
  phone: string;
  email: string | null;
  country_interest: string | null;
  attestat_avg: number | null;
  message: string | null;
  status: string;
  created_at: string;
}

export interface AuditLogRow {
  id: string;
  user_id: string | null;
  action: string;
  table_name: string;
  row_id: string | null;
  before: Record<string, unknown> | null;
  after: Record<string, unknown> | null;
  created_at: string;
}

type MakeInsert<Row, Auto extends keyof Row> = Omit<Row, Auto> & Partial<Pick<Row, Auto>>;

export interface Database {
  public: {
    Tables: {
      countries: {
        Row: CountriesRow;
        Insert: MakeInsert<CountriesRow, "id" | "created_at" | "updated_at" | "is_deleted" | "deleted_at">;
        Update: Partial<CountriesRow>;
      };
      universities: {
        Row: UniversitiesRow;
        Insert: MakeInsert<UniversitiesRow, "id" | "created_at" | "updated_at" | "is_deleted" | "deleted_at">;
        Update: Partial<UniversitiesRow>;
      };
      faculties: {
        Row: FacultiesRow;
        Insert: MakeInsert<FacultiesRow, "id" | "is_deleted" | "deleted_at">;
        Update: Partial<FacultiesRow>;
      };
      university_fees: {
        Row: UniversityFeesRow;
        Insert: MakeInsert<UniversityFeesRow, "is_deleted" | "deleted_at">;
        Update: Partial<UniversityFeesRow>;
      };
      faqs: {
        Row: FaqsRow;
        Insert: MakeInsert<FaqsRow, "id" | "is_deleted" | "deleted_at">;
        Update: Partial<FaqsRow>;
      };
      testimonials: {
        Row: TestimonialsRow;
        Insert: MakeInsert<TestimonialsRow, "id" | "is_deleted" | "deleted_at">;
        Update: Partial<TestimonialsRow>;
      };
      site_content: {
        Row: SiteContentRow;
        Insert: MakeInsert<SiteContentRow, "updated_at" | "is_deleted" | "deleted_at">;
        Update: Partial<SiteContentRow>;
      };
      applications: {
        Row: ApplicationsRow;
        Insert: MakeInsert<ApplicationsRow, "id" | "created_at" | "status">;
        Update: Partial<ApplicationsRow>;
      };
      audit_log: {
        Row: AuditLogRow;
        Insert: MakeInsert<AuditLogRow, "id" | "created_at">;
        Update: Partial<AuditLogRow>;
      };
    };
  };
}

export type CountriesInsert = Database["public"]["Tables"]["countries"]["Insert"];
export type CountriesUpdate = Database["public"]["Tables"]["countries"]["Update"];
export type UniversitiesInsert = Database["public"]["Tables"]["universities"]["Insert"];
export type UniversitiesUpdate = Database["public"]["Tables"]["universities"]["Update"];
export type FacultiesInsert = Database["public"]["Tables"]["faculties"]["Insert"];
export type FacultiesUpdate = Database["public"]["Tables"]["faculties"]["Update"];
export type UniversityFeesInsert = Database["public"]["Tables"]["university_fees"]["Insert"];
export type UniversityFeesUpdate = Database["public"]["Tables"]["university_fees"]["Update"];
export type FaqsInsert = Database["public"]["Tables"]["faqs"]["Insert"];
export type FaqsUpdate = Database["public"]["Tables"]["faqs"]["Update"];
export type TestimonialsInsert = Database["public"]["Tables"]["testimonials"]["Insert"];
export type TestimonialsUpdate = Database["public"]["Tables"]["testimonials"]["Update"];
export type SiteContentInsert = Database["public"]["Tables"]["site_content"]["Insert"];
export type SiteContentUpdate = Database["public"]["Tables"]["site_content"]["Update"];
export type ApplicationsInsert = Database["public"]["Tables"]["applications"]["Insert"];
export type ApplicationsUpdate = Database["public"]["Tables"]["applications"]["Update"];
export type AuditLogInsert = Database["public"]["Tables"]["audit_log"]["Insert"];
export type AuditLogUpdate = Database["public"]["Tables"]["audit_log"]["Update"];
